---
- name: Deploy VM in AWS
  hosts: all
  vars:
    ec2_password: ""
    inventory_name: "AWS_RHPDS"
    win_admin_user: "default"
    win_admin_pass: "default"
  
  tasks:
################### Add Hosts ###################
    - name: Add new node to Contrller inventory
      host:
        name: "{{ windows_instances.results.0.instances.0.tags.Name }}_{{ windows_instances.results.0.instances.0.id }}"
        inventory: "{{ inventory_name }}"
        variables:
          #hostname: "{{ windows_instances.results.0.instances.0.tags.Name }}_{{ windows_instances.results.0.instances.0.id }}"
          ansible_host: "{{ windows_instances.results.0.instances.0.public_dns_name }}"
          ansible_password: "{{ ec2windows_password.win_password }}"
          #groups: "{{ windows_instances.results.0.instances.0.tags.os_type }} "
 
################### Wait for Instances ################### 
    - name: Windows | Wait for {{ windows_ansible_connection | default('winrm') }} to come up
      wait_for_connection:
      delegate_to: "{{ item }}"
      with_items: "{{ groups['windows'] }}"
      ignore_errors: true
      
################### Set Password Fact ###################
    - name: Set password fact for subsequent job templates
      set_stats:
        data:
          ec2_password: "{{ ec2_password.win_password }}"

################### Local Admin from Controller ###################
    - name: Create Local Admin User
      win_user:
        name: "{{ win_admin_user }}"
        password: "{{ win_admin_pass }}"
        password_never_expires: true   
        groups: Administrators
        state: present
        register: localadministrator_result
