---
- name: Add VM to Controller inventory
  hosts: localhost
  vars:
    vm_name: ""
    vm_hostname: ""
    vm_password: ""
    vm_key: ""
    group_name: ""
    inventory_name: ""
    aws_instance: ""
  
  tasks:
    - name: Add new node to Controller inventory
      ansible.controller.host:
        name: "{{ vm_name }}"
        inventory: "{{ inventory_name }}"
        validate_certs: no
        variables:
          ansible_host: "{{ vm_hostname }}"
          ansible_password: "{{ vm_password }}"
          instance_id: "{{ aws_instance }}"
          ansible_ssh_private_key_file: "{{ vm_key }}"

    - name: Add new node to Group
      ansible.controller.group:
        name: "{{ group_name }}"
        inventory: "{{ inventory_name }}"
        validate_certs: no
        preserve_existing_hosts: yes
        preserve_existing_children: yes
        hosts: "{{ vm_name }}"
