---
- name: Add VM to Controller inventory
  hosts: all
  vars:
    vm_name: ""
    vm_hostname: ""
    vm_password: ""
    inventory_name: "AWS_RHPDS"
    win_admin_user: "default"
    win_admin_pass: "default"
  
  tasks:
################### Add Hosts ###################
    - name: Add new node to Controller inventory
      host:
        name: "{{ vm_name }}"
        inventory: "{{ inventory_name }}"
        variables:
          ansible_host: "{{ vm_hostname }}"
          ansible_password: "{{ vm_password }}"
          #groups: "{{ windows_instances.results.0.instances.0.tags.os_type }} "
 
################### Wait for Instances ################### 
    - name: Windows | Wait for {{ windows_ansible_connection | default('winrm') }} to come up
      wait_for_connection:
      delegate_to: "{{ item }}"
      with_items: "{{ groups['windows'] }}"
      ignore_errors: true

################### Local Admin from Controller ###################
    - name: Create Local Admin User
      win_user:
        name: "{{ win_admin_user }}"
        password: "{{ win_admin_pass }}"
        password_never_expires: true   
        groups: Administrators
        state: present
        register: localadministrator_result
