---
- name: Delete VM from Controller inventory
  hosts: localhost
  vars:
    vm_name: ""
    vm_hostname: ""
    vm_password: ""
    group_name: ""
    inventory_name: ""
    aws_instance: ""
  
  tasks:
    - name: Delete node from Controller inventory
      ansible.controller.host:
        name: "{{ vm_name }}"
        inventory: "{{ inventory_name }}"
        validate_certs: no
