---
- name: Upload a file to GIT
  hosts: localhost
  gather_facts: False
  vars:
    dest_dir: /tmp/git
    email: bla@bla.com
    repo: https://github.com/shaunhofer/ansible.git
    
  tasks:   
    - name: Clone Git repository
      git:
        repo: "{{ repo }}"
        dest: "{{ dest_dir }}"
      become: true
      
    - name: Set Git details
      git_config:
        name: user.name
        scope: global
        repo: "{{ dest_dir }}"
        value: "shaunhofer"
        
    - name: Set Git details
      command: git config --global user.name "shaunhofer"
      become: true
      
    - name: Set Git details
      command: git config --global user.email "{{ email }}"
      become: true
      
    - name: Copy file to Git repository
      copy:
        src: /etc/hostname
        dest: "{{ dest_dir }}/F5/backup"
      become: true
    
    - name: Add to Git repository
      command: git add {{ item }}
      with_items:
        - "{{ dest_dir }}/F5/backup"
      args:
        chdir: "{{ dest_dir }}/F5/backup"
      become: true
    
    - name: commit INTIAL to Git repository
      command: git commit -m "initial commit"
      args:
        chdir: "{{ dest_dir }}/F5/backup"
      become: true
    
    #- name: commit file to Git repository
    #  command: git commit -m "Adding {{ item }}"
    #  with_items:
    #    - "{{ dest_dir }}/F5/backup"
    #  args:
    #    chdir: "{{ dest_dir }}/F5/backup"
    #  become: true

    - name: Set remote repo
      command: git remote set-url origin git@github.com:shaunhofer/ansible.git
      args:
        chdir: "{{ dest_dir }}"
      become: true

    - name: Check GIT remote
      command: git remote -v 
      args:
        chdir: "{{ dest_dir }}"
      become: true
      
    - name: Check SSH keys
      command: ssh-keyscan github.com >> ~/.ssh/known_hosts
      become: true

    - name: Push changes to Git repository
      command: git push origin main
      args:
        chdir: "{{ dest_dir }}"
      become: true
