---
- name: Upload a file to GIT
  hosts: localhost
  gather_facts: False
  vars:
    dest_dir: /tmp/git
    email: bla@bla.com
    repo: https://github.com/shaunhofer/ansible.git
    
  tasks:   
    - name: Clone Git repository
      git:
        repo: "{{ repo }}"
        dest: "{{ dest_dir }}"
      become: true
      
    - name: Set Git details
      git_config:
        name: user.name
        scope: global
        repo: "{{ dest_dir }}"
        value: "shaunhofer"
        
    - name: Set Git details
      command: git config --global user.name "shaunhofer"
      become: true
      
    - name: Set Git details
      command: git config --global user.email "{{ email }}"
      become: true
      
    - name: Copy file to Git repository
      copy:
        src: /etc/hostname
        dest: "{{ dest_dir }}/F5/backup"
      become: true
    
    - name: Add to Git repository
      command: git add {{ item }}
      with_items:
        - "{{ dest_dir }}/F5/backup"
      args:
        chdir: "{{ dest_dir }}/F5/backup"
      become: true
    
    - name: commit INTIAL to Git repository
      command: git commit -m "initial commit"
      args:
        chdir: "{{ dest_dir }}/F5/backup"
      become: true
    
    #- name: commit file to Git repository
    #  command: git commit -m "Adding {{ item }}"
    #  with_items:
    #    - "{{ dest_dir }}/F5/backup"
    #  args:
    #    chdir: "{{ dest_dir }}/F5/backup"
    #  become: true

    - name: Set remote repo
      command: git remote set-url origin git@github.com:shaunhofer/ansible.git
      args:
        chdir: "{{ dest_dir }}"
      become: true

    - name: Check GIT remote
      command: git remote -v 
      args:
        chdir: "{{ dest_dir }}"
      become: true
      
    - name: SSH known hosts
      command: ssh-keyscan github.com >> /etc/ssh/ssh_known_hosts
      
    #- name: Update known hosts for ssh #https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints
    #  ansible.builtin.known_hosts:
    #    name: guthub.com
     #   key: github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=  #  (ECDSA)
     #   path: /etc/ssh/ssh_known_hosts
     #   state: present

    - name: Cat known_hosts
      command: cat /etc/hostname
      become: true

    - name: Push changes to Git repository
      command: git push origin main
      args:
        chdir: "{{ dest_dir }}"
      become: true
