---
############## f5 node ##############
- name: find ami for F5 BIG-IP
  ec2_ami_info:
    region: "{{ ec2_region }}"
    owners: "{{ ec2_info.f5node.owners }}"
    filters:
      name: "{{ ec2_info.f5node.filter }}"
      architecture: "{{ ec2_info.f5node.architecture }}"
  register: amis

- name: save ami for F5
  set_fact:
    f5_ami: >
      {{ amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}

- name: Create instances for F5 BIG-IP node(s)
  amazon.aws.ec2_instance:
    key_name: "{{ ec2_name_prefix }}-key"
    security_group: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_info.f5node.size }}"
    image_id: "{{ f5_ami.image_id }}"
    region: "{{ ec2_region }}"
    exact_count: 1
    state: running
    network:
      assign_public_ip: true
    filters:
      instance-state-name: running
      "tag:Workshop_f5": "{{ ec2_name_prefix }}-f5"
    wait: "{{ ec2_wait }}"
    # vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    volumes:
      - device_name: /dev/xvda
        ebs:
          volume_type: "{{ ec2_info['f5node'].disk_volume_type }}"
          volume_size: "{{ ec2_info['f5node'].disk_space }}"
          iops: "{{ ec2_info['f5node'].disk_iops }}"
          throughput: "{{ ec2_info['f5node'].disk_throughput }}"
          delete_on_termination: true
  register: f5_test

- debug:
    msg: "{{ f5_test }}"

- name: grab instance ids to tag f5 node
  amazon.aws.ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Workshop_f5": "{{ ec2_name_prefix }}-f5"
  register: f5_output