# Play 1:  Connect  List or Install Patches on Remote servers
- name: Discover Patches
  hosts: all
  become: yes
  environment:
    StrictHostKeyChecking: no
  gather_facts: yes  
  
  tasks:
    - name: Load Patching Role
      include_role:
        name: linux_patching
      vars:
        patch_mode: discover


# Play 2:  Combine Server Lists and send email
- name: Combine All Server Patching Lists (Localhost)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    master_csv_file: "./master_csv_report.csv"
    advisory_csv_file: "./advisory_csv_report.csv"

  tasks:

    - name: Combine all Server Lists
      set_fact:
        master_server_patch_list: "{{ master_server_patch_list|default([])  + hostvars[item]['server_patch_list']  }}"
        advisory_server_patch_list: "{{ advisory_server_patch_list|default([])  + hostvars[item]['advisory_list']  }}"
      with_inventory_hostnames:
        - all
      when: hostvars[item]['server_patch_list'] is defined

      

    - name: Enumerate the Master List
      ansible.builtin.debug:
        var: master_server_patch_list
      
    - name: Enumerate the Advisory List
      ansible.builtin.debug:
        var: advisory_server_patch_list
       

    - name: Create Master CSV
      template:
        src: report.csv.j2
        dest: "{{ master_csv_file }}"

    - name: Create Advisory CSV
      template:
        src: advisory_report.csv.j2
        dest: "{{ advisory_csv_file }}"

    # - name: pause for 5 minutes
    #   pause:
    #     minutes: 5

    - name: Patching  notification by email
      mail:
        host: "{{ email_server }}"
        port: "{{ email_port}}"
        from: "{{ email_user }}"
        to: "{{ to_email }}" 
        subject: "Patching Discovery Report"
        subtype: html
        username: "{{ email_user }}"
        password: "{{ email_pass }}"
        body: "Patching Report Attached"
        attach:
          - "{{ master_csv_file }}"
          - "{{ advisory_csv_file }}"

