---
#- name: Download apt sources file
  #become: yes
  #ansible.builtin.git:
  #get_url:
    #url: https://raw.githubusercontent.com/shaunhofer/ansible/main/Linux/sources.list
    #dest: /etc/apt/sources.list

- name: APT update
  become: yes
  ansible.builtin.apt:
    update_cache: yes
  

  
- name: Check for upgradeable
  become: yes
  #check_mode: yes
  ansible.builtin.command: apt list --upgradable
  #ansible.builtin.apt:
    #upgrade: yes
    #name: "*"
  register: upgradeable

- name: show results of upgradeable
  debug:
    var: upgradeable
