---
- name: Deploy windows VM in AWS
  hosts: localhost
  vars:
    instance_loc: aws
    name: "Ansibledemo"
    ec2_vpc_id: "vpc-0bcde310b604499c6"
    ec2_region: "ap-southeast-2"
    ec2_az: "ap-southeast-2a"
    tag_user: "ansible"
    user_count: "1"
    ec2_instance_type: "t2.medium"
    ec2_vpc_subnet_id: "subnet-0b0bfa69219481a33"
    ec2_ami_image: "ami-0be7afce90ae33ee9" #Microsoft Windows Server 2022 Base
    ptr_zone_cidr: "10.10.1.0/24"
    security_group: Ansibledemo-windowssg
    # Needed for AD and windows client provision
    dns_domain_name: "ansibleworkshop.com"
    dns_domain_name_short: "ansibleworkshop"
    ldap_basedn: "DC=ansibleworkshop,DC=com"
    domain_admin_password: "$t0p read1ng My @ss"
    aws_key_name: ""
    aws_key_pair: ""



################### Private key ###################
  tasks:
    - name: Create key pair {{ aws_key_name  }}
      ec2_key:
        name: "{{ aws_key_name }}"
        region: "{{ ec2_region }}"
      register: create_key
      
    - name: Save the private key
      copy:
        content: "{{ create_key.key.private_key }}"
        dest: "/root/{{ aws_key_name }}-VM-private.pem"
        mode: '0400'
      when: create_key.changed
      
################### Build Instances ###################      
    - name: Windows - Launch instance 1
      ec2:
        key_name: "{{ aws_key_name }}"
        instance_type: "{{ ec2_instance_type }}"
        image: "{{ ec2_ami_image }}"
        wait: yes
        count: 1
        group: "{{ security_group }}"
        vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
        assign_public_ip: yes
        region: "{{ ec2_region }}"
        count_tag:
          Name: "{{ name }}"
          App: AnsibleWorkshop
        instance_tags:
          Name: "{{ name }}"
          App: AnsibleWorkshop
          Username: "{{ tag_user }}"
          Info: "Username that provisioned this-> {{ tag_user }}"
          short_name: "{{ name }}"
          long_name: "{{ name }}.{{ public_dns_zone | default('') }}"
          os_type: windows
        user_data: "{{ lookup('template', 'win_ec2_user_data.j2', template_vars=dict(vm_name='s' + item )) }}"
      with_sequence: count={{user_count}}
      register: windows_jobs
      async: 7200
      poll: 0
       
################### Wait for Jobs ###################
    - name: Wait for windows instance creation to complete
      async_status: jid="{{ item.ansible_job_id }}"
      register: windows_instances
      until: windows_instances.finished
      retries: 300
      with_items:
        - "{{ windows_jobs.results }}"

    - name: show results of windowes_instances
      debug:
        var: windows_instances.results

################### Get Passwords ###################
    - name: Windows | Obtain windows passwords for instances
      ec2_win_password:
        region: '{{ ec2_region }}'
        instance_id: "{{ windows_instances.results.0.instances.0.id }}"
        key_file: "/root/{{ aws_key_name }}-VM-private.pem"
        #key_data: "{{ create_key.key.private_key }}"  
        #wait: yes
        #wait_timeout: 60
        #with_items: "{{ windows_instances.results | map(attribute='tagged_instances') | list }}"
      register: ec2windows_password
        #when: windows_instances is defined and os_type == 'windows'

################### Add Hosts ###################

    - name: Windows | Add new instance to host group
      add_host:
        hostname: "{{ name }}"
        ansible_host: "{{ name }}.{{ public_dns_zone | default('') }}"
        private_ip: "{{ item.item.private_ip }}"
        ansible_port: "5986"
        ansible_user: "Administrator"
        ansible_password: "{{ item.win_password }}"
        ansible_become_password: "{{ item.win_password }}"
        ansible_connection: "{{ windows_ansible_connection | default('winrm') }}"
        ansible_shell_type: "cmd"
        ansible_winrm_transport: "CredSSP"
        ansible_winrm_server_cert_validation: "ignore"
        ansible_winrm_operation_timeout_sec: 120
        ansible_winrm_read_timeout_sec: 150
        #student: "{{ item.item.tags.Student | regex_replace('[^0-9]', '') }}"
        groups: windows
      with_items: "{{ ec2windows_password.results }}"
      #when: ec2windows_password is defined
 
 ################### Wait for Instances ################### 

    - name: Windows | Wait for {{ windows_ansible_connection | default('winrm') }} to come up
      wait_for_connection:
      delegate_to: "{{ item }}"
      with_items: "{{ groups['windows'] }}"
    
################### Set Stats ###################

    - name: Set password fact for subsequent job templates
      set_stats:
        data:
          ec2windows_password: "{{ item.win_password }}"
        # per_host: yes
      with_items: "{{ ec2windows_password.results }}"
