---
- name: Deploy VPC, subnets, gateway and SG
  hosts: localhost
  vars:
    instance_loc: aws
    name_prefix: "Ansibledemo"
    ec2_vpc_id: ""
    ec2_region: "{{ survey_ec2_region }}"
    ec2_az: "{{ survey_ec2_az }}"
    user_count: "1"
    ec2_vpc_subnet_id: ""
    ptr_zone_cidr: "{{ survey_ptr_zone_cidr }}"

    ################### Create Resources ###################
  tasks:
    - name: Create AWS VPC {{ name_prefix }}-vpc
      ec2_vpc_net:
        name: "{{ name_prefix }}-vpc"
        cidr_block: "{{ ptr_zone_cidr }}"
        region: "{{ ec2_region }}"
      register: create_vpc
      until: create_vpc is not failed
      retries: 5

    - name: Set VPC ID
      set_fact:
        ec2_vpc_id: "{{ create_vpc.vpc.id }}"

    - name: Create subnet for {{ name_prefix }}-vpc
      ec2_vpc_subnet:
        region: "{{ ec2_region }}"
        az: "{{ ec2_az }}"
        vpc_id: "{{ ec2_vpc_id }}"
        cidr: "{{ ptr_zone_cidr }}"
        wait_timeout: 600
        resource_tags:
          Name: "{{ name_prefix }}-subnet"
      register: create_subnet
      until: create_subnet is not failed
      retries: 15

    - name: Set Subnet ID
      set_fact:
        ec2_vpc_subnet_id: "{{ create_subnet.subnet.id }}"
        
    ################### Gateway and routing ###################
    - name: Create Internet Gateway
      ec2_vpc_igw:
        vpc_id: "{{ ec2_vpc_id }}"
        region: "{{ ec2_region }}"
        state: present
      register: igw
      until: igw is not failed
      retries: 15

    - name: vpc public subnet route table is present for {{ ec2_vpc_id }}
      ec2_vpc_route_table:
        region: "{{ ec2_region }}"
        vpc_id: "{{ ec2_vpc_id }}"
        subnets:
          - "{{ ec2_vpc_subnet_id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
        tags:
          Name: "{{ name_prefix }}-route"
      register: routetable
      until: routetable is not failed
      retries: 5

    ################### Create Security Groups ###################

    - name: Create security group
      ec2_group:
        name: "{{ name_prefix }}-sg"
        description: "Windows and Linux SG"
        vpc_id: "{{ ec2_vpc_id }}"
        region: "{{ ec2_region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "0.0.0.0/0"
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 5986
            to_port: 5986
            cidr_ip: "0.0.0.0/0"
          - proto: tcp
            from_port: 3389
            to_port: 3389
            cidr_ip: "0.0.0.0/0"
          - proto: all
            cidr_ip: "{{ ptr_zone_cidr }}"
