---
- name: Deploy VM in AWS
  hosts: localhost
  vars:
    instance_name: "Ansibledemo"
    ec2_region: "ap-southeast-2"
    aws_key_name: "AnsibleDemoKey"
  tasks:
  
  ################### Delete Private key ###################
    - name: Delete Key Pair {{ aws_key_name  }}
      ec2_key:
        name: "{{ aws_key_name }}"
        region: "{{ ec2_region }}"
        state: absent
      register: remove_key
      ignore_errors: true
      
################### Delete Instances ###################      
    - name: Delete Instances
      amazon.aws.ec2_instance:
        region: "{{ ec2_region }}"
        name:  "{{ instance_name }}"
        state: absent
        wait: yes
        wait_timeout: 600
        filters:
          instance-state-name: running
      register: delete_job
      
