---
- name: Snapshot VM instance
  hosts: localhost
  gather_facts: False

  vars:
    instance_id: ""
    region_id: "ap-southeast-2"
    
  tasks:
  
    - name: Snapshot VM instance primary disk
      ec2_snapshot:
        region: "{{ region_id }}"
        instance_id: "{{ instance_id }}"
        device_name: "/dev/sdb1"
        description: Quick snapshot before work
