---
- name: Deploy AS3 JSON
  hosts: lb
  gather_facts: false
  environment:
    #F5_TEEM: false
    no_f5_teem: true
  collections:
    - f5networks.f5_bigip
    
  vars:
    json_loc: ~/AS3_send.json
    pool_members: "{{ groups['web'] }}"
    as3:
      class: AS3
      action: deploy
      persist: true
      declaration:
        class: ADC
        schemaVersion: 3.22.0
        id: id
        label: WebApp
        ansible:
          class: Tenant
          A1:
            class: Application
            web:
              class: Service_HTTP
              virtualAddresses:
              - 10.1.2.3
              virtualPort: 80
              pool: web_pool
            web_pool:
              class: Pool
              monitors:
              - use: http_mon
              members:
              - servicePort: 8080
                serverAddresses:
                - 10.2.2.3
            http_mon:
              class: Monitor
              monitorType: http
              receive: I AM UP
      
  tasks:
    - name: Create JSON file locally
      ansible.builtin.copy:
        dest: "{{ json_loc }}" 
        content: "{{ as3 | to_json }}" 
      delegate_to: localhost
      #register: f5_as3_deploy_request
    
   - name: Check json file
     ansible.builtin.command: cat "{{ json_loc }}" 
     register: f5_as3_deploy_request
    
    - name: Debug
      debug:
        var: f5_as3_deploy_request
    
    - name: PUSH JSON to AS3
      f5networks.f5_bigip.bigip_as3_deploy:
          content: "{{ lookup('template', '{{ json_loc }}') }}"
          state: present
      tags: [ deploy ]
      connection: local
      
      #delegate_to: localhost
