---
- name: Deploy AS3 JSON #https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/gslb.html#using-big-ip-dns-features-in-a-declaration
  hosts: lb
  gather_facts: false
  connection: httpapi
  vars:
    post_action: deploy
    json_loc: ~/AS3_send.json
    pool_members: "{{ groups['web'] }}"
    as3:
      class: ADC
      #action: "{{ post_action }}"
      updateMode: selective
      schemaVersion: 3.0.0
      id: DNS
      Sample_non_http_03:
        class: Tenant
        TEST_DNS_Zone:
          class: Application
          dnsZone:
            class: DNS_Zone
            label: dnsZone
            remark: DNS Zone test
            dnsExpress:
              enabled: true
              nameserver:
                use: dnsNameserverZone
              notifyAction: consume
              allowNotifyFrom:
              - 10.1.1.1
              verifyNotifyTsig: false
            responsePolicyEnabled: true
            serverTsigKey:
              use: tsigKeyZone
            transferClients:
            - use: dnsNameserverZone
          dnsNameserverZone:
            class: DNS_Nameserver
            label: dnsNameserverZone
            address: 10.1.1.2
            port: 53
            routeDomain:
              bigip: "/Common/0"
            tsigKey:
              use: tsigKeyZone
          tsigKeyZone:
            class: DNS_TSIG_Key
            label: tsigKeyZone
            remark: TSIG Key test
            algorithm: hmacmd5
            secret:
              ciphertext: ZjVmNQ==
              miniJWE: true
              protected: eyJhbGciOiJkaXIiLCJlbmMiOiJub25lIn0
              ignoreChanges: true
              allowReuse: false
      DNS_PROFILE_1:
        class: Tenant
        DNS_PROFILE_1:
          class: Application
          service:
            class: Service_UDP
            virtualPort: 80
            virtualAddresses:
            - 198.19.192.210
            profileUDP:
              use: profileUdp
            profileDNS:
              use: profileDnsHW
          profileDnsLogging:
            class: DNS_Logging_Profile
            remark: DNS Logging Profile test
            includeCompleteAnswer: true
            includeQueryId: false
            includeSource: true
            includeTimestamp: true
            includeView: true
            logPublisher:
              bigip: "/Common/local-db-publisher"
            logQueriesEnabled: true
            logResponsesEnabled: false
          profileDnsHW:
            class: DNS_Profile
            label: profileDnsHW
            remark: DNS Profile test
            parentProfile:
              bigip: "/Common/dns"
            rapidResponseEnabled: false
            rapidResponseLastAction: allow
            hardwareQueryValidationEnabled: true
            hardwareResponseCacheEnabled: true
            dnssecEnabled: false
            globalServerLoadBalancingEnabled: false
            dnsExpressEnabled: false
            cacheEnabled: false
            dns64Mode: secondary
            dns64Prefix: 0:0:0:0:0:0:0:0
            dns64AdditionalSectionRewrite: any
            unhandledQueryAction: drop
            localBindServerEnabled: false
            zoneTransferEnabled: true
            recursionDesiredEnabled: false
            securityEnabled: false
            loggingEnabled: true
            loggingProfile:
              use: profileDnsLogging
            statisticsSampleRate: 20
          profileUdp:
            class: UDP_Profile
            datagramLoadBalancing: true

  tasks:
    - name: Create JSON file locally
      copy:
        dest: "{{ json_loc }}" 
        content: "{{ as3 | to_json }}" 
      delegate_to: localhost
  
    - name: PUSH JSON to AS3
      uri:
        url: "https://{{ ansible_host }}:8443/mgmt/shared/appsvcs/declare"
        method: POST
        body: "{{ lookup('file', '{{ json_loc }}' ) }}"
        status_code: 200
        timeout: 300
        body_format: json
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      delegate_to: localhost
