---
- name: BIG-IP BACKUP
  hosts: lb
  connection: local
  gather_facts: false
  collections:
    - f5networks.f5_bigip
  vars:
    local_folder_location: "/tmp/f5/"
    file_name: UseCase-00-backup.ucs

  tasks:
    - name: Setting up provider values
      set_fact:
       provider:
        server: "{{private_ip}}"
        server_port: "8443"
        validate_certs: "False"
        
    - name: Create a new UCS
      bigip_ucs_fetch:
        provider: "{{provider}}"
        dest: /tmp/cs_backup.ucs
      register: task
      
    - name: Check for task completion and download created UCS
      bigip_ucs_fetch:
        dest: /tmp/cs_backup.ucs
        src: "{{ task.src }}"
        task_id: "{{ task.task_id }}"
        timeout: 300
