---
- name: BIG-IP BACKUP
  hosts: lb
  connection: local
  gather_facts: false
  collections:
    - f5networks.f5_bigip
  vars:
    local_file: "/tmp/cs_backup.ucs"
    file_name: UseCase-00-backup.ucs
    mynfs: "192.168.0.200:/nfs/share"
    mountpoint: "/share"
    permission: '0777'
    myopts: 'rw,sync'

  tasks:
    - name: Setting up provider values
      set_fact:
       provider:
        server: "{{ private_ip }}"
        server_port: "8443"
        validate_certs: "False"
        
    - name: Create a new UCS
      bigip_ucs_fetch:
        provider: "{{ provider }}"
        dest: "/tmp/cs_backup.ucs"
      register: task
     
    - name: displays task
      debug:
        var: task
     
    - name: Check for task completion and download created UCS
      bigip_ucs_fetch:
        dest: "{{ local_file }}"
        src: "{{ task.src }}"
        timeout: 300
        
    - name: Call upload endpoints
      uri:
        url: "url to use"
        method: "POST"
        body_format: "form-multipart"
        body:
          backup:
            filename: "{{ playbook_dir + '/files/file.pdf' }}"
            mime_type: application/octet-stream
          anotherFormParam: "api_key"
        user: "user"
        password: "pass"
        force_basic_auth: yes
        return_content: yes
        headers:
          Content-Type: multipart/form-data
        validate_certs: false
      register: upload_result
