---
- name: Display qkview details
  hosts: lb
  connection: local
  gather_facts: false
  collections:
    - f5networks.f5_modules
  vars:
    isopath: /tmp/X.iso
    
  tasks:
    - name: Setting up provider values
      set_fact:
       provider:
        server: "{{private_ip}}"
        server_port: "8443"
        validate_certs: "False"
        
    - name: Upload absolute image to the BIG-IP
      bigip_software_image:
        image: "{{isopath}}"
        provider: "{{provider}}"
      delegate_to: localhost
