---
- name: Upgrade BigIP
  hosts: lb
  connection: local
  gather_facts: false
  collections:
    - f5networks.f5_modules
  vars:
    iso: X.iso
    volume: HD1.1
    mount_point: /mnt/nfs
    nfs_server: 0.0.0.0  
    nfs_path: /
    isopath: "{{ mount_point }}/{{ iso }}"
    permission: '0770'
    nfsopts: 'ro,sync,nfsvers=3'
    
  tasks:
    #- name: Install NFS client packages
    #  dnf:
    #    name: nfs-utils
    #    state: present

    - name: Create mount point
      file:
        path: "{{ mount_point }}"
        state: directory
        mode: "{{ permission }}"
        owner: root
      delegate_to: localhost
      become: true
    
    #- name: Mount error
    #  command: "mount -t nfs -o {{ nfsopts }} -vvvvvv {{ nfs_server }}:{{ nfs_path }} {{ mount_point }}" 
    #  become: true
    #  delegate_to: localhost
    
    #- name: Mount NFS share
    #  mount:
    #    fstype: nfs
    #    src: "{{ nfs_server }}:{{ nfs_path }}"
    #    path: "{{ mount_point }}"
    #    state: mounted
    #    opts: "{{ nfsopts }}"
    #  become: true
    #  delegate_to: localhost
    
    - name: Setting up provider values
      set_fact:
       provider:
        server: "{{ private_ip }}"
        server_port: "8443"
        validate_certs: "False"
        
    #- name: Upload absolute image to the BIG-IP
    #  bigip_software_image:
    #    image: "{{isopath}}"
    #    provider: "{{ provider }}"
    #  delegate_to: localhost
      
    - name: Ensure an existing image is installed in specified volume
      bigip_software_install:
        image: "{{ iso }}"
        volume: "{{ volume }}"
        state: installed
        provider: "{{ provider }}"
      
    - name: Ensure an existing image is activated in specified volume
      bigip_software_install:
        image: "{{ iso }}"
        volume: "{{ volume }}"
        state: installed
        provider: "{{provider}}"
