---
- name: Display qkview details
  hosts: lb
  connection: local
  gather_facts: false
  collections:
    - f5networks.f5_modules
  vars:
    fileloc: /tmp/localhost.localdomain.qkview
    
  tasks:
    - name: Setting up provider values
      set_fact:
       provider:
        server: "{{private_ip}}"
        server_port: "8443"
        validate_certs: "False"
        
    - name: Fetch a qkview from the remote device
      bigip_qkview:
        provider: "{{provider}}"
        asm_request_log: yes
        exclude:
          - all
          - audit
          - secure
          - bash_history
        dest: "{{ fileloc }}"
       
    - name: Cat known_hosts
      command: cat "{{ fileloc }}"
      become: true
      #debug: msg="the value of qkview is {{lookup('file', '"{{ fileloc }}"') }}"
