---
- name: Display qkview details
  hosts: lb
  connection: local
  gather_facts: false
  collections:
    - f5networks.f5_modules
  vars:
    fileloc: /tmp/localhost.localdomain.qkview
    
  tasks:
    - name: Fetch a qkview from the remote device
      bigip_qkview:
        asm_request_log: yes
        exclude:
          - audit
          - secure
        dest: "{{ fileloc }}"
       
    - name: Print qkview
      command: cat "{{ fileloc }}"
      #debug: msg="the value of qkview is {{lookup('file', '"{{ fileloc }}"') }}"
